### ISSUE TITLE
Batch size and iterations

### ISSUE THREAD

**Issue by fuqianya** [ezeli/BUTD_model#7]
Hi, thanks for your great works! I am wondering should I increase the batch size since it will take about 3 hours to train per epoch on single NVIDIA 1080Ti. I am new to image captioning and do not know if the batch size could harm to the performance. Finally, how many iterations should to be updated to get the performance in the Readme. Looking for your rely. Thanks.

**Comment by ezeli** [comment]
In my experience, batch size does not have much impact on performance. And in order to speed up the training, you can increase the parameter [num_workers](https://github.com/ezeli/BUTD_model/blob/163e82cef70b04462bf8eaf2319c0a3368863849/opts.py#L14). It takes about 30 epochs to achieve this performance.

**Comment by fuqianya** [comment]
I have reproduced the results, so I closed it!
